name: First Action
on: [workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@v3
            - name: Install dependencies
              run: nvm use && npm ci
            - name: Run tests
              run: npm run test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - name: Deploy artifact
            run: echo "Artifact deployed."