name: First Action
on: [workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: '16.18.1'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
            - name: Output context
              run: echo "${{ toJson(github)}}"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - name: Deploy artifact
            run: echo "Artifact deployed."